stages:
    - build

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
    paths:
        - .m2/repository

build:
    stage: build
    tags:
        - shared
    image: maven:latest
    script:
        - mvn versions:set -DnewVersion=$CI_COMMIT_REF_NAME
        - mvn package
    artifacts:
        paths:
            - target/*.jar
    rules:
        - if: $CI_COMMIT_TAG
